
-- HDD interface (ProDOS)


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity hdd is
  port (
    CLK_14M        : in std_logic;
    IO_SELECT      : in std_logic;
    DEVICE_SELECT  : in std_logic;
    RESET          : in std_logic;
    A              : in unsigned(15 downto 0);
    RD             : in std_logic;
    D_IN           : in unsigned(7 downto 0);
    D_OUT          : out unsigned(7 downto 0);
    sector         : out unsigned(15 downto 0);
    hdd_read       : out std_logic;
    hdd_write      : out std_logic;
    hdd_mounted    : in std_logic;
    hdd_protect    : in std_logic;

    ram_addr       : in unsigned(8 downto 0);
    ram_di         : in unsigned(7 downto 0);
    ram_do         : out unsigned(7 downto 0);
    ram_we         : in std_logic
  );
end hdd;

architecture rtl of hdd is

  -- BRAM component (generated by Vivado Block Memory Generator)

  component hdd_sector_bram
    port (
      clka  : in  std_logic;
      ena   : in  std_logic;
      wea   : in  std_logic;
      addra : in  std_logic_vector(8 downto 0);
      dina  : in  std_logic_vector(7 downto 0);
      douta : out std_logic_vector(7 downto 0);

      clkb  : in  std_logic;
      enb   : in  std_logic;
      web   : in  std_logic;
      addrb : in  std_logic_vector(8 downto 0);
      dinb  : in  std_logic_vector(7 downto 0);
      doutb : out std_logic_vector(7 downto 0)
    );
  end component;

 
  -- Interface registers

  signal rom_dout      : unsigned(7 downto 0);
  signal reg_status    : unsigned(7 downto 0);
  signal reg_command   : unsigned(7 downto 0);
  signal reg_unit      : unsigned(7 downto 0);
  signal reg_mem_l     : unsigned(7 downto 0);
  signal reg_mem_h     : unsigned(7 downto 0);
  signal reg_block_l   : unsigned(7 downto 0);
  signal reg_block_h   : unsigned(7 downto 0);

  signal sec_addr            : unsigned(8 downto 0);
  signal increment_sec_addr  : std_logic;
  signal select_d            : std_logic;


  -- BRAM signals

  signal cpu_we      : std_logic := '0';
  signal dma_we      : std_logic := '0';
  signal cpu_ram_out : std_logic_vector(7 downto 0);
  signal dma_ram_out : std_logic_vector(7 downto 0);


  -- ProDOS constants

  constant PRODOS_COMMAND_STATUS   : unsigned := X"00";
  constant PRODOS_COMMAND_READ     : unsigned := X"01";
  constant PRODOS_COMMAND_WRITE    : unsigned := X"02";
  constant PRODOS_COMMAND_FORMAT   : unsigned := X"03";
  constant PRODOS_STATUS_NO_DEVICE : unsigned := X"28";
  constant PRODOS_STATUS_PROTECT   : unsigned := X"2B";

begin

  sector <= reg_block_h & reg_block_l;


  -- CPU interface

  cpu_interface : process (CLK_14M)
  begin
    if rising_edge(CLK_14M) then

      D_OUT     <= X"FF";
      hdd_read  <= '0';
      hdd_write <= '0';
      cpu_we    <= '0';

      if RESET = '1' then
        reg_status   <= X"00";
        reg_command  <= X"00";
        reg_unit     <= X"00";
        reg_mem_l    <= X"00";
        reg_mem_h    <= X"00";
        reg_block_l  <= X"00";
        reg_block_h  <= X"00";
        sec_addr     <= (others => '0');
        increment_sec_addr <= '0';

      else
        select_d <= DEVICE_SELECT;

        if DEVICE_SELECT = '1' then

      
          -- CPU READ
      
          if RD = '1' then
            case A(3 downto 0) is

              when X"0" =>
                sec_addr <= (others => '0');
                case reg_command is
                  when PRODOS_COMMAND_STATUS =>
                    if hdd_mounted = '1' and reg_unit = X"70" then
                      reg_status <= X"00";
                      D_OUT      <= X"00";
                    else
                      reg_status <= X"01";
                      D_OUT      <= PRODOS_STATUS_NO_DEVICE;
                    end if;

                  when PRODOS_COMMAND_READ =>
                    if hdd_mounted = '1' and reg_unit = X"70" then
                      hdd_read   <= '1';
                      reg_status <= X"00";
                      D_OUT      <= X"00";
                    else
                      reg_status <= X"01";
                      D_OUT      <= PRODOS_STATUS_NO_DEVICE;
                    end if;

                  when PRODOS_COMMAND_WRITE =>
                    if hdd_mounted = '0' or reg_unit /= X"70" then
                      D_OUT      <= PRODOS_STATUS_NO_DEVICE;
                      reg_status <= X"01";
                    elsif hdd_protect = '1' then
                      D_OUT      <= PRODOS_STATUS_PROTECT;
                    else
                      D_OUT      <= X"00";
                      reg_status <= X"00";
                      hdd_write  <= '1';
                    end if;

                  when others =>
                    null;
                end case;

              when X"1" => D_OUT <= reg_status;
              when X"2" => D_OUT <= reg_command;
              when X"3" => D_OUT <= reg_unit;
              when X"4" => D_OUT <= reg_mem_l;
              when X"5" => D_OUT <= reg_mem_h;
              when X"6" => D_OUT <= reg_block_l;
              when X"7" => D_OUT <= reg_block_h;

              when X"8" =>
                D_OUT <= unsigned(cpu_ram_out);
                increment_sec_addr <= '1';

              when others =>
                null;
            end case;

          -- CPU WRITE
      
          else
            case A(3 downto 0) is

              when X"2" =>
                if D_IN = X"02" then
                  sec_addr <= (others => '0');
                end if;
                reg_command <= D_IN;

              when X"3" => reg_unit <= D_IN;
              when X"4" => reg_mem_l <= D_IN;
              when X"5" => reg_mem_h <= D_IN;
              when X"6" => reg_block_l <= D_IN;
              when X"7" => reg_block_h <= D_IN;

              when X"8" =>
                cpu_we <= '1';
                increment_sec_addr <= '1';

              when others =>
                null;
            end case;
          end if;

        elsif DEVICE_SELECT = '0' and select_d = '1' then
          if increment_sec_addr = '1' then
            sec_addr <= sec_addr + 1;
            increment_sec_addr <= '0';
          end if;

        elsif IO_SELECT = '1' then
          if RD = '1' then
            D_OUT <= rom_dout;
          end if;
        end if;
      end if;
    end if;
  end process;

  -- External DMA RAM port

  dma_port : process(CLK_14M)
  begin
    if rising_edge(CLK_14M) then
      dma_we <= ram_we;
      ram_do <= unsigned(dma_ram_out);
    end if;
  end process;


  -- BRAM instance
  u_sector_bram : hdd_sector_bram
    port map (
      -- CPU port (C0F8)
      clka  => CLK_14M,
      ena   => '1',
      wea   => cpu_we,
      addra => std_logic_vector(sec_addr),
      dina  => std_logic_vector(D_IN),
      douta => cpu_ram_out,

      -- DMA port
      clkb  => CLK_14M,
      enb   => '1',
      web   => dma_we,
      addrb => std_logic_vector(ram_addr),
      dinb  => std_logic_vector(ram_di),
      doutb => dma_ram_out
    );

  -- HDD ROM
  rom : entity work.hdd_rom
    port map (
      addr => A(7 downto 0),
      clk  => CLK_14M,
      dout => rom_dout
    );

end rtl;