-------------------------------------------------------------------------------
--
-- PS/2 Keyboard interface for the Apple //e
--
-- Szombathelyi György
--
-- Based on
-- PS/2 Keyboard interface for the Apple ][
--
-- Stephen A. Edwards, sedwards@cs.columbia.edu
--
-- After an original by Alex Freed
--
-------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;


entity keyboard_apple is
   port (
      CLK_14M        : in  std_logic;

      PS2_Key        : in  std_logic_vector(10 downto 0);

      mega65_caps    : in  std_logic;
      mega65_alt_i   : in  std_logic;

      -- '0' = original Apple positional mapping
      -- '1' = MEGA65 glyph-oriented mapping
      mega65_layout_i : in std_logic;

      reads          : in  std_logic;
      reset          : in  std_logic;

      akd            : buffer std_logic;
      K              : out unsigned(7 downto 0);

      open_apple     : out std_logic;
      closed_apple   : out std_logic;

      soft_reset     : out std_logic := '0';

      video_toggle   : out std_logic := '0';
      palette_toggle : out std_logic := '0'
   );
end keyboard_apple;


architecture rtl of keyboard_apple is


   ---------------------------------------------------------------------------
   -- Keyboard ROM
   ---------------------------------------------------------------------------

   signal q_signal      : std_logic_vector(7 downto 0);
   signal rom_addr      : std_logic_vector(10 downto 0);
   signal rom_out       : unsigned(7 downto 0);


   ---------------------------------------------------------------------------
   -- Key decoding
   ---------------------------------------------------------------------------

   signal junction_code : std_logic_vector(7 downto 0);

   signal code          : unsigned(7 downto 0);
   signal latched_code  : unsigned(7 downto 0);

   signal ext           : std_logic;
   signal latched_ext   : std_logic;


   ---------------------------------------------------------------------------
   -- MEGA65 glyph translation
   ---------------------------------------------------------------------------

   signal effective_shift    : std_logic;
   signal force_shift        : std_logic;
   signal force_unshift      : std_logic;

   signal effective_junction : std_logic_vector(7 downto 0);
   signal suppress_key       : std_logic;


   ---------------------------------------------------------------------------
   -- Keyboard state
   ---------------------------------------------------------------------------

   signal key_pressed : std_logic;

   signal ctrl        : std_logic;
   signal shift       : std_logic;
   signal caplock     : std_logic;

   signal old_stb     : std_logic;

   signal rep_timer   : unsigned(22 downto 0);


   ---------------------------------------------------------------------------
   -- Special PS/2 keyboard codes
   ---------------------------------------------------------------------------

   constant LEFT_SHIFT  : unsigned(7 downto 0) := x"12";
   constant RIGHT_SHIFT : unsigned(7 downto 0) := x"59";
   constant LEFT_CTRL   : unsigned(7 downto 0) := x"14";
   constant CAPS_LOCK   : unsigned(7 downto 0) := x"58";

   constant WINDOWS     : unsigned(7 downto 0) := x"1F";
   constant ALT         : unsigned(7 downto 0) := x"11";

   constant F13         : unsigned(7 downto 0) := x"06";
   constant F8          : unsigned(7 downto 0) := x"0A";
   constant F9          : unsigned(7 downto 0) := x"01";
   

   ---------------------------------------------------------------------------
   -- State machine
   ---------------------------------------------------------------------------

   type states is (
      IDLE,
      HAVE_CODE,
      DECODE,
      GOT_KEY_UP_CODE,
      GOT_KEY_UP2,
      KEY_UP,
      NORMAL_KEY,
      KEY_READY1,
      KEY_READY
   );

   signal state      : states;
   signal next_state : states;


begin


   ---------------------------------------------------------------------------
   -- Keyboard ROM output
   ---------------------------------------------------------------------------

   rom_out <= unsigned(q_signal);


   ---------------------------------------------------------------------------
   -- MEGA65 private pseudo scan codes
   --
   -- These pseudo codes are generated by keyboard_adapter and are not real
   -- PS/2 scan codes.
   --
   -- F0 = :
   -- F1 = @
   -- F2 = *
   -- F3 = +
   -- F4 = "
   -- F5 = &
   -- F6 = '
   -- F7 = (
   -- F8 = )
   -- F9 = #
   -- FA = no-op
   -- FB = ;
   ---------------------------------------------------------------------------

   force_shift <= '1' when
        latched_code = x"F1" or
        latched_code = x"F2" or
        latched_code = x"F3" or
        latched_code = x"F4" or
        latched_code = x"F5" or
        latched_code = x"F7" or
        latched_code = x"F8" or
        latched_code = x"F9" or
        latched_code = x"FD" or  -- ~
        latched_code = x"FE"     -- |
    else '0';


   force_unshift <= '1' when
      latched_code = x"F6"      -- '
   else '0';


   ---------------------------------------------------------------------------
   -- Effective shift state
   --
   -- Normally this simply follows the physical Shift state.
   --
   -- Pseudo codes can force Shift on/off for dedicated MEGA65 symbol keys.
   --
   -- Additionally, MEGA65 Shift+7 must generate a single quote. Since the
   -- Apple quote matrix position produces " when shifted, Shift is suppressed
   -- for that particular held key.
   ---------------------------------------------------------------------------

   effective_shift <=
   ------------------------------------------------------------------------
   -- MEGA65 : / [ / {
   ------------------------------------------------------------------------

   -- ALT+: = {
   '1' when mega65_layout_i = '1' and
            mega65_alt_i = '1' and
            latched_code = x"F0" else
   -- Shift+: = [
   '0' when latched_code = x"F0" and
            shift = '1' else
   -- plain : = :
   '1' when latched_code = x"F0" else

   ------------------------------------------------------------------------
   -- MEGA65 ; / ] / }
   ------------------------------------------------------------------------

   -- ALT+; = }
   '1' when mega65_layout_i = '1' and
            mega65_alt_i = '1' and
            latched_code = x"FB" else
   -- plain ; and Shift+; use an unshifted Apple matrix position
   '0' when latched_code = x"FB" else


    -- ALT+, = ~
    '1' when mega65_layout_i = '1' and
             mega65_alt_i = '1' and
             latched_code = x"EC" else
    
    -- ALT+. = |
    '1' when mega65_layout_i = '1' and
             mega65_alt_i = '1' and
             latched_code = x"ED" else

    -- ALT+/ = \
    '0' when mega65_layout_i = '1' and
             mega65_alt_i = '1' and
             latched_code = x"EE" else
    
    -- ALT+= = _
    '1' when mega65_layout_i = '1' and
             mega65_alt_i = '1' and
             latched_code = x"EB" else
             
    -- Shift+= must remain =
    '0' when mega65_layout_i = '1' and
             latched_code = x"EB" else
             
   ------------------------------------------------------------------------
   -- Existing special cases
   ------------------------------------------------------------------------

   '0' when force_unshift = '1' else
   -- MEGA65 Shift+7 = '
   '0' when mega65_layout_i = '1' and
            shift = '1' and
            latched_code = x"3D" else
    -- MEGA65 Shift+- should remain -
   '0' when mega65_layout_i = '1' and
             shift = '1' and
             latched_code = x"4E" else
   '1' when force_shift = '1' else

   shift;

   ---------------------------------------------------------------------------
   -- Dynamic MEGA65 shifted number-row translation
   --
   -- This is deliberately done HERE rather than in keyboard_adapter.
   --
   -- This means:
   --
   --    hold Shift, then press 6 -> &
   --
   -- and:
   --
   --    hold 6, then press Shift -> &
   --
   -- behave identically.
   --
   -- The currently-held key remains latched while Shift can change at any
   -- time, so auto-repeat also changes to the correct glyph.
   ---------------------------------------------------------------------------

   mega65_shifted_keys : process(all)
    begin
    
       effective_junction <= junction_code;
       suppress_key       <= '0';
    
    
       ------------------------------------------------------------------------
       -- Dedicated MEGA65 : / [ / { key
       ------------------------------------------------------------------------
       if latched_code = x"F0" then
    
          if mega65_layout_i = '1' and mega65_alt_i = '1' then
             -- ALT + : key = {
             -- Apple [ matrix position with Shift active
             effective_junction <= x"3A";
          elsif shift = '1' then
    
             -- Shift + : key = [
             effective_junction <= x"3A";
          else
    
             -- : key = :
             effective_junction <= x"1C";
          end if;
    
    
       ------------------------------------------------------------------------
       -- Dedicated MEGA65 ; / ] / } key
       ------------------------------------------------------------------------
       elsif latched_code = x"FB" then
    
          if mega65_layout_i = '1' and mega65_alt_i = '1' then
             -- ALT + ; key = }
             -- Apple ] matrix position with Shift active
             effective_junction <= x"3B";
    
          elsif shift = '1' then
             -- Shift + ; key = ]
             effective_junction <= x"3B";
          else
             -- ; key = ;
             effective_junction <= x"1C";
          end if;
    
        ------------------------------------------------------------------------
        -- MEGA65 , / ~ key
        ------------------------------------------------------------------------
        elsif latched_code = x"EC" then
        
           if mega65_layout_i = '1' and mega65_alt_i = '1' then
              effective_junction <= x"2E";  -- ~
           else
              effective_junction <= x"25";  -- ,
           end if;
        
        ------------------------------------------------------------------------
        -- MEGA65 . / | key
        ------------------------------------------------------------------------
        elsif latched_code = x"ED" then
        
           if mega65_layout_i = '1' and mega65_alt_i = '1' then
              effective_junction <= x"38";  -- |
           else
              effective_junction <= x"26";  -- .
           end if;
        
        ------------------------------------------------------------------------
        -- MEGA65 / / \ key
        ------------------------------------------------------------------------
        elsif latched_code = x"EE" then
        
           if mega65_layout_i = '1' and mega65_alt_i = '1' then
              effective_junction <= x"38";  -- \
           else
              effective_junction <= x"27";  -- /
           end if;
        
        ------------------------------------------------------------------------
        -- MEGA65 = / _ key
        ------------------------------------------------------------------------
        elsif latched_code = x"EB" then
        
           if mega65_layout_i = '1' and mega65_alt_i = '1' then
              -- ALT + = = _
              effective_junction <= x"31";  -- Apple - key
           else
              -- normal =
              effective_junction <= x"2F";
           end if;
    
       ------------------------------------------------------------------------
       -- Existing MEGA65 shifted number-row handling
       ------------------------------------------------------------------------
       elsif mega65_layout_i = '1' and shift = '1' then
          case latched_code is
             when x"1E" =>              -- 2
                effective_junction <= x"45";  -- "
             when x"36" =>              -- 6
                effective_junction <= x"07";  -- &
             when x"3D" =>              -- 7
                effective_junction <= x"45";  -- '
             when x"3E" =>              -- 8
                effective_junction <= x"09";  -- (
             when x"46" =>              -- 9
                effective_junction <= x"30";  -- )
             when x"45" =>              -- 0
                suppress_key <= '1';
             when others =>
                null;
          end case;
       end if;
    end process mega65_shifted_keys;


   ---------------------------------------------------------------------------
   -- Keyboard ROM
   ---------------------------------------------------------------------------

   keyboard_rom : entity work.dualport_2clk_ram
      generic map (
         ADDR_WIDTH   => 11,
         DATA_WIDTH   => 8,
         ROM_PRELOAD  => true,
         ROM_FILE     => "../../CORE/Apple-II_MiSTer-master/rtl/roms/keyboard.hex",
         ROM_FILE_HEX => true
      )
      port map (
         clock_a   => CLK_14M,
         wren_a    => '0',
         address_a => std_logic_vector(rom_addr),
         data_a    => (others => '0'),

         clock_b   => CLK_14M,
         address_b => std_logic_vector(rom_addr),
         data_b    => (others => '0'),
         q_b       => q_signal
      );


   ---------------------------------------------------------------------------
   -- Apple keyboard output
   ---------------------------------------------------------------------------

   K <= key_pressed & rom_out(6 downto 0);


   ---------------------------------------------------------------------------
   -- Caps Lock
   ---------------------------------------------------------------------------

   caplock_ctrl : process(CLK_14M, reset)
   begin

      if reset = '1' then
         caplock <= '0';
      elsif rising_edge(CLK_14M) then
         -- Caps Lock is already tracked by the MEGA65 keyboard framework.
         caplock <= not mega65_caps;
      end if;

   end process caplock_ctrl;


   ---------------------------------------------------------------------------
   -- Modifier / special-key state
   ---------------------------------------------------------------------------

   shift_ctrl : process(CLK_14M, reset)
   begin

      if reset = '1' then

         shift          <= '0';
         ctrl           <= '0';

         open_apple     <= '0';
         closed_apple   <= '0';

         soft_reset     <= '0';
         video_toggle   <= '0';
         palette_toggle <= '0';


      elsif rising_edge(CLK_14M) then


         ---------------------------------------------------------------
         -- Key press
         ---------------------------------------------------------------

         if state = HAVE_CODE then
            if code = LEFT_SHIFT or code = RIGHT_SHIFT then
               shift <= '1';
            elsif code = LEFT_CTRL then
               ctrl <= '1';
            elsif code = WINDOWS then
               open_apple <= '1';
            elsif code = ALT then
               closed_apple <= '1';
            elsif code = F13 and ctrl = '1' then
               soft_reset <= '1';
            elsif code = F8 then
               palette_toggle <= '1';
            elsif code = F9 then
               video_toggle <= '1';
            end if;


         ---------------------------------------------------------------
         -- Key release
         ---------------------------------------------------------------

         elsif state = KEY_UP then
            if code = LEFT_SHIFT or code = RIGHT_SHIFT then
               shift <= '0';
            elsif code = LEFT_CTRL then
               ctrl <= '0';
            elsif code = WINDOWS then
               open_apple <= '0';
            elsif code = ALT then
               closed_apple <= '0';
            elsif code = F13 then
               soft_reset <= '0';
            elsif code = F8 then
               palette_toggle <= '0';
            elsif code = F9 then
               video_toggle <= '0';

            end if;

         end if;

      end if;

   end process shift_ctrl;


   ---------------------------------------------------------------------------
   -- Incoming scan code
   ---------------------------------------------------------------------------

   code <= unsigned(PS2_Key(7 downto 0));
   ext  <= PS2_Key(8);


   ---------------------------------------------------------------------------
   -- Keyboard state machine
   ---------------------------------------------------------------------------

   fsm : process(CLK_14M, reset)
   begin

      if reset = '1' then

         state        <= IDLE;
         latched_code <= (others => '0');
         latched_ext  <= '0';

         key_pressed  <= '0';
         akd          <= '0';

         old_stb      <= '0';
         rep_timer    <= (others => '0');


      elsif rising_edge(CLK_14M) then

         state <= next_state;


         ---------------------------------------------------------------
         -- Apple has read the key
         ---------------------------------------------------------------

         if reads = '1' then
            key_pressed <= '0';
         end if;


         ---------------------------------------------------------------
         -- Accept new keyboard event toggle
         ---------------------------------------------------------------

         if state = HAVE_CODE then
            old_stb <= PS2_Key(10);
         end if;


         ---------------------------------------------------------------
         -- Key release
         ---------------------------------------------------------------

         if state = GOT_KEY_UP_CODE then
            akd <= '0';
         end if;


         ---------------------------------------------------------------
         -- Latch normal key
         ---------------------------------------------------------------

         if state = NORMAL_KEY then

            latched_code <= code;
            latched_ext  <= ext;

         end if;


         ---------------------------------------------------------------
         -- Valid character from keyboard ROM
         ---------------------------------------------------------------

         if state = KEY_READY and
            junction_code /= x"FF" and
            suppress_key = '0'
         then

            akd         <= '1';
            key_pressed <= '1';

            -- Initial key-repeat delay: approximately 0.5 seconds.
            rep_timer <= to_unsigned(7000000, 23);

         end if;


         ---------------------------------------------------------------
         -- Auto repeat
         ---------------------------------------------------------------

         if akd = '1' then

            rep_timer <= rep_timer - 1;

            if rep_timer = 0 then
               rep_timer <= to_unsigned(933333, 23);
               
               -- Shift+0 in MEGA65 layout deliberately generates nothing.
               if suppress_key = '0' then
                  key_pressed <= '1';
               else
                  key_pressed <= '0';
               end if;

            end if;

         end if;

      end if;

   end process fsm;


   ---------------------------------------------------------------------------
   -- State-machine combinational logic
   ---------------------------------------------------------------------------

   fsm_next_state : process(code, old_stb, PS2_Key, state)
   begin

      next_state <= state;


      case state is


         when IDLE =>

            if old_stb /= PS2_Key(10) then
               next_state <= HAVE_CODE;
            end if;


         when HAVE_CODE =>

            next_state <= DECODE;


         when DECODE =>

            if PS2_Key(9) = '0' then

               next_state <= GOT_KEY_UP_CODE;

            elsif
               code = LEFT_SHIFT  or
               code = RIGHT_SHIFT or
               code = LEFT_CTRL   or
               code = CAPS_LOCK
            then

               next_state <= IDLE;

            else

               next_state <= NORMAL_KEY;

            end if;


         when GOT_KEY_UP_CODE =>
            next_state <= GOT_KEY_UP2;

         when GOT_KEY_UP2 =>
            next_state <= KEY_UP;

         when KEY_UP =>
            next_state <= IDLE;

         when NORMAL_KEY =>
            next_state <= KEY_READY1;

         when KEY_READY1 =>
            next_state <= KEY_READY;

         when KEY_READY =>
            next_state <= IDLE;

      end case;

   end process fsm_next_state;


   ---------------------------------------------------------------------------
   -- Keyboard ROM address
   --
   -- The Apple keyboard ROM uses:
   --
   -- caplock
   -- keyboard matrix junction
   -- CTRL
   -- SHIFT
   --
   -- effective_junction/effective_shift allow the MEGA65 glyph layout to
   -- translate its different shifted keycap arrangement.
   ---------------------------------------------------------------------------

   rom_addr <=
      '0' &
      caplock &
      effective_junction(6 downto 0) &
      not ctrl &
      not effective_shift;


   ---------------------------------------------------------------------------
   -- PS/2 scan code -> Apple IIe keyboard matrix junction
   ---------------------------------------------------------------------------

   with latched_ext & std_logic_vector(latched_code) select

      junction_code <=

         ---------------------------------------------------------------
         -- Main keyboard
         ---------------------------------------------------------------

         x"00" when '0' & x"76", -- Escape

         x"01" when '0' & x"16", -- 1
         x"02" when '0' & x"1E", -- 2
         x"03" when '0' & x"26", -- 3
         x"04" when '0' & x"25", -- 4
         x"05" when '0' & x"36", -- 6
         x"06" when '0' & x"2E", -- 5
         x"07" when '0' & x"3D", -- 7
         x"08" when '0' & x"3E", -- 8
         x"09" when '0' & x"46", -- 9
         x"0A" when '0' & x"0D", -- Tab
         x"0B" when '0' & x"15", -- Q
         x"0C" when '0' & x"1D", -- W
         x"0D" when '0' & x"24", -- E
         x"0E" when '0' & x"2D", -- R
         x"0F" when '0' & x"35", -- Y
         x"10" when '0' & x"2C", -- T
         x"11" when '0' & x"3C", -- U
         x"12" when '0' & x"43", -- I
         x"13" when '0' & x"44", -- O
         x"14" when '0' & x"1C", -- A
         x"15" when '0' & x"23", -- D
         x"16" when '0' & x"1B", -- S
         x"17" when '0' & x"33", -- H
         x"18" when '0' & x"2B", -- F
         x"19" when '0' & x"34", -- G
         x"1A" when '0' & x"3B", -- J
         x"1B" when '0' & x"42", -- K
         x"1C" when '0' & x"4C", -- ;
         x"1D" when '0' & x"4B", -- L
         x"1E" when '0' & x"1A", -- Z
         x"1F" when '0' & x"22", -- X
         x"20" when '0' & x"21", -- C
         x"21" when '0' & x"2A", -- V
         x"22" when '0' & x"32", -- B
         x"23" when '0' & x"31", -- N
         x"24" when '0' & x"3A", -- M
         x"25" when '0' & x"41", -- ,
         x"26" when '0' & x"49", -- .
         x"27" when '0' & x"4A", -- /


         ---------------------------------------------------------------
         -- Keypad / additional Apple positions
         ---------------------------------------------------------------

         x"28" when '1' & x"4A", -- KP /

         x"2A" when '0' & x"70", -- KP 0
         x"2B" when '0' & x"69", -- KP 1
         x"2C" when '0' & x"72", -- KP 2
         x"2D" when '0' & x"7A", -- KP 3
         x"2E" when '0' & x"5D", -- `
         x"2F" when '0' & x"55", -- =
         x"30" when '0' & x"45", -- 0
         x"31" when '0' & x"4E", -- -
         x"34" when '0' & x"6B", -- KP 4
         x"35" when '0' & x"73", -- KP 5
         x"36" when '0' & x"74", -- KP 6
         x"37" when '0' & x"6C", -- KP 7
         x"38" when '0' & x"0E", -- \
         x"39" when '0' & x"4D", -- P
         x"3A" when '0' & x"54", -- [
         x"3B" when '0' & x"5B", -- ]
         x"3C" when '0' & x"7C", -- KP *
         x"3E" when '0' & x"75", -- KP 8
         x"3F" when '0' & x"7D", -- KP 9
         x"40" when '0' & x"71", -- KP .
         x"41" when '0' & x"79", -- KP +
         x"42" when '0' & x"5A", -- Return
         x"43" when '1' & x"75", -- Up arrow
         x"44" when '0' & x"29", -- Space
         x"45" when '0' & x"52", -- '
         x"49" when '0' & x"7B", -- KP -
         x"4A" when '1' & x"5A", -- KP Return
         x"4C" when '1' & x"71", -- Delete
         x"4E" when '0' & x"66", -- Backspace
         x"4D" when '1' & x"72", -- Down
         x"4E" when '1' & x"6B", -- Left
         x"4F" when '1' & x"74", -- Right


         ---------------------------------------------------------------
         -- MEGA65 private glyph pseudo codes
         ---------------------------------------------------------------

         x"1C" when '0' & x"F0", -- : -> Apple ; + forced shift
         x"02" when '0' & x"F1", -- @ -> Apple 2 + forced shift
         x"08" when '0' & x"F2", -- * -> Apple 8 + forced shift
         x"2F" when '0' & x"F3", -- + -> Apple = + forced shift
         x"45" when '0' & x"F4", -- " -> quote + forced shift
         x"07" when '0' & x"F5", -- & -> Apple 7 + forced shift
         x"45" when '0' & x"F6", -- ' -> quote + forced unshift
         x"09" when '0' & x"F7", -- ( -> Apple 9 + forced shift
         x"30" when '0' & x"F8", -- ) -> Apple 0 + forced shift
         x"03" when '0' & x"F9", -- # -> Apple 3 + forced shift
         x"2E" when '0' & x"FC", -- ` from MEGA65 ALT+<-
         x"2E" when '0' & x"FD", -- ~ from MEGA65 ALT+.
         x"38" when '0' & x"FE", -- | from MEGA65 ALT+.
         x"38" when '0' & x"EF", -- \ from MEGA65 ALT+/
         x"25" when '0' & x"EC", -- MEGA65 comma key
         x"26" when '0' & x"ED", -- MEGA65 dot key
         x"27" when '0' & x"EE", -- MEGA65 slash key
         x"2F" when '0' & x"EB", -- MEGA65 = key
         
         ---------------------------------------------------------------
         -- FA deliberately has NO mapping.
         --
         -- Used for MEGA65 Shift+0 where the keycap has no shifted glyph.
         ---------------------------------------------------------------


         ---------------------------------------------------------------
         -- Shift+] = ;
         --
         -- Physical Shift remains held, therefore this pseudo code forces
         -- the Apple keyboard ROM to treat the semicolon matrix key as
         -- unshifted.
         ---------------------------------------------------------------

         x"1C" when '0' & x"FB",


         ---------------------------------------------------------------
         -- Unknown / unsupported code
         ---------------------------------------------------------------

         x"FF" when others;


end rtl;